version: '3.8'
services:

  #MySQL Service
  db:
    hostname: db
    container_name: db
    image: 'yobasystems/alpine-mariadb:latest'
    environment:
      MYSQL_ROOT_PASSWORD: 'db'
      MYSQL_DATABASE: 'marktwerking'
      MYSQL_USER: 'dbuser'
      MYSQL_PASSWORD: 'dbpass'
    volumes:
      - dbdata:/var/lib/mysql/ # allows you to stop and restart the db service without losing data
      - ./etc/mysql/my.cnf:/etc/mysql/my.cnf
      - ./html:/docker-entrypoint-initdb.d
    networks:
      - net
    restart: always

  #PHP Service
  php:
    hostname: php
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    depends_on: 
      - db
    environment:
      - MW_DB_HOST=db
      - MW_DB_USERNAME=dbuser
      - MW_DB_PASSWORD=dbpass
      - MW_DB_DATABASE=marktwerking
      - MW_BAR_PASSWORD=MW21
    tty: true
    ports:
      - 4080:80
    volumes:
      - ./html:/var/www/html
      - "./etc/php/local.ini:/usr/local/etc/php/conf.d/local.ini"
    networks:
      - net

#Docker Networks
networks:
  net:
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 192.168.31.0/29 #192.168.31.1 - 192.168.31.6 (bc:7)
    driver_opts:
     com.docker.network.bridge.name: web_net
volumes:
  dbdata:
    driver: local
